application:
  port: 8000
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my_secret_token"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  db_name: "newsletter"
  password: "password"
